volumes:
  db: {}

services:
  postgres:
    image: postgres:18
    environment:
      - "POSTGRES_USER=nebula"
      - "POSTGRES_PASSWORD=nebula"
      - "POSTGRES_DB=nebula"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "db:/var/lib/postgresql"
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped

  server:
    image: nebulabroadcast/nebula-server:latest
    ports:
      - "4455:80"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./plugins:/plugins"
      - "./settings:/settings"
      - "./storage:/mnt/nebula_01"
    depends_on:
      - redis
      - postgres


  hls-server:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - nebula-storage:/srv/nebula:ro
      - ./nginx-hls.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server
      - worker

  worker:
    image: nebulabroadcast/nebula-worker:latest
    hostname: worker
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./storage:/mnt/nebula_01"
    privileged: true

    depends_on:
      - server
